//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Assignment {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Assignment.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter: The text you entered is not a valid number.
        /// </summary>
        internal static string errorFormatException {
            get {
                return ResourceManager.GetString("errorFormatException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter: Salary cannot be negative.
        /// </summary>
        internal static string errorNegativeSalary {
            get {
                return ResourceManager.GetString("errorNegativeSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect parameter: The number you entered does not fit within a byte.
        /// </summary>
        internal static string errorOverflowException {
            get {
                return ResourceManager.GetString("errorOverflowException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,12}.
        /// </summary>
        internal static string formatSalaryPrintout {
            get {
                return ResourceManager.GetString("formatSalaryPrintout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-20}: {1,17:c0}.
        /// </summary>
        internal static string formatSalaryStats {
            get {
                return ResourceManager.GetString("formatSalaryStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press any key to continue (escape to exit).
        /// </summary>
        internal static string promptContinue {
            get {
                return ResourceManager.GetString("promptContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter salary #{0}: .
        /// </summary>
        internal static string promptEnterSalary {
            get {
                return ResourceManager.GetString("promptEnterSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify number of salaries to enter: .
        /// </summary>
        internal static string promptNumberSalaries {
            get {
                return ResourceManager.GetString("promptNumberSalaries", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average salary.
        /// </summary>
        internal static string statsAverageSalary {
            get {
                return ResourceManager.GetString("statsAverageSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median salary.
        /// </summary>
        internal static string statsMedianSalary {
            get {
                return ResourceManager.GetString("statsMedianSalary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Salary dispersion.
        /// </summary>
        internal static string statsSalaryDispersion {
            get {
                return ResourceManager.GetString("statsSalaryDispersion", resourceCulture);
            }
        }
    }
}
